/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ConsultationBooking = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const ITAuditRequest = IDL.Record({
  'id' : IDL.Nat,
  'contactName' : IDL.Text,
  'itChallenges' : IDL.Text,
  'preferredAuditDate' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});
export const ConsultationBookingInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDateTime' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const ContactFormInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const ITAuditRequestInput = IDL.Record({
  'contactName' : IDL.Text,
  'itChallenges' : IDL.Text,
  'preferredAuditDate' : IDL.Text,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'phone' : IDL.Text,
  'industry' : IDL.Text,
});

export const idlService = IDL.Service({
  'getConsultationBookings' : IDL.Func(
      [],
      [IDL.Vec(ConsultationBooking)],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getITAuditRequests' : IDL.Func([], [IDL.Vec(ITAuditRequest)], ['query']),
  'submitConsultationBooking' : IDL.Func(
      [ConsultationBookingInput],
      [Result],
      [],
    ),
  'submitContactForm' : IDL.Func([ContactFormInput], [Result], []),
  'submitITAuditRequest' : IDL.Func([ITAuditRequestInput], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ConsultationBooking = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ITAuditRequest = IDL.Record({
    'id' : IDL.Nat,
    'contactName' : IDL.Text,
    'itChallenges' : IDL.Text,
    'preferredAuditDate' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  const ConsultationBookingInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDateTime' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const ContactFormInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ITAuditRequestInput = IDL.Record({
    'contactName' : IDL.Text,
    'itChallenges' : IDL.Text,
    'preferredAuditDate' : IDL.Text,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'phone' : IDL.Text,
    'industry' : IDL.Text,
  });
  
  return IDL.Service({
    'getConsultationBookings' : IDL.Func(
        [],
        [IDL.Vec(ConsultationBooking)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getITAuditRequests' : IDL.Func([], [IDL.Vec(ITAuditRequest)], ['query']),
    'submitConsultationBooking' : IDL.Func(
        [ConsultationBookingInput],
        [Result],
        [],
      ),
    'submitContactForm' : IDL.Func([ContactFormInput], [Result], []),
    'submitITAuditRequest' : IDL.Func([ITAuditRequestInput], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };